# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FireBaseChat' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!


#  pod 'FirebaseCore', '~> 4.0'
#  pod 'FirebaseStorage', '~> 2.1'
#  pod 'FirebaseRemoteConfig', '~> 2.1'
#  pod 'FirebaseDatabase', '~> 4.1'
#  pod 'FirebaseRemoteConfig', '~> 2.1'
    pod 'JSQMessagesViewController', '~> 7.3'
    pod 'Firebase/Core'
    pod 'Firebase/Storage'
    pod 'Firebase/Auth'
    pod 'Firebase/Database'
    pod 'Firebase/RemoteConfig'
    pod 'GooglePlaces'
    pod 'GooglePlacePicker'

#  pod 'Firebase', '~> 4.7'
#  pod 'FirebaseDatabase', '~> 4.1'
#  pod 'FirebaseAuth', '~> 4.4'
#  pod 'Firebase/Core'
#  pod 'Firebase/Storage'
#  pod 'Firebase/Auth'
#  pod 'Firebase/Database'
#  pod 'Firebase/RemoteConfig'

end
